name: mobile/beta
on:
  push:
    branches: [beta]
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  expo:
    uses: ./.github/workflows/mobile-expo.yaml
    with: { profile: beta }
    secrets: inherit
