name: server/build
on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }
    secrets:
      SENTRY_AUTH_TOKEN:
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions: { contents: read, packages: write, attestations: write, id-token: write }
    env:
      IMAGE: ghcr.io/${{ github.repository }}-${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, fetch-tags: true }
      - uses: docker/setup-buildx-action@v3 # cspell:ignore buildx
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=sha,format=long
            type=ref,event=pr
            type=ref,event=branch
            type=match,pattern=^(?!@)(.*)$,group=1,event=tag
            type=match,pattern=@exactly\/server@(\d+\.\d+\.\d+.*),group=1
            type=match,pattern=@exactly\/server@(\d+\.\d+),group=1
            type=match,pattern=@exactly\/server@(\d+),group=1
      - uses: docker/login-action@v3
        with: { registry: ghcr.io, username: "${{ github.repository_owner }}", password: "${{ secrets.GITHUB_TOKEN }}" }
      - uses: docker/build-push-action@v6
        id: build
        with:
          push: true
          context: .
          file: server/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CHAIN_ID=${{ vars.CHAIN_ID }}
            APP_DOMAIN=${{ vars.APP_DOMAIN }}
            EXPO_PUBLIC_DEVTOOLS=${{ vars.EXPO_PUBLIC_DEVTOOLS }}
      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.IMAGE }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
      - run: |
          docker pull ${{ env.IMAGE }}@${{ steps.build.outputs.digest }}
          docker create --name extract ${{ env.IMAGE }}@${{ steps.build.outputs.digest }}
          docker cp extract:/prod/server/dist ./server/dist
          mkdir -p ./server/generated
          docker cp extract:/prod/server/generated/release.js ./server/generated/release.js
          docker rm extract
          echo "release=$(node -e 'console.log(require(`./server/generated/release`))')" >> $GITHUB_OUTPUT
        id: extract
      - uses: getsentry/action-release@v3 # cspell:ignore getsentry
        if: inputs.environment == 'production'
        env: { SENTRY_ORG: exactly, SENTRY_PROJECT: server, SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}" }
        with:
          environment: ${{ inputs.environment }}
          release: ${{ steps.extract.outputs.release }}
          sourcemaps: server/dist
          inject: false
