name: substreams/sandbox
on: { workflow_run: { workflows: [substreams/build], types: [completed] } }
jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'sandbox'
    uses: ./.github/workflows/substreams-deploy.yaml
    secrets: inherit
    with: { environment: sandbox }
